services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    # network_mode: host
    restart: always
    environment:
      OLLAMA_BASE_URL: http://127.0.0.1:11434
    ports:
      - "8181:8080" # Change the host port (8080 -> 8181)
    volumes:
      - open-webui:/app/backend/data

volumes:
  open-webui:
